"""Add 3 columns at device model.

Revision ID: 3573db9fea6b
Revises: bb9fe138639e
Create Date: 2021-01-11 11:15:15.978387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3573db9fea6b'
down_revision = 'bb9fe138639e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('can_count', sa.Integer(), nullable=False))
    op.add_column('device', sa.Column('license', sa.VARCHAR(length=50), nullable=False))
    op.add_column('device', sa.Column('lin_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'lin_count')
    op.drop_column('device', 'license')
    op.drop_column('device', 'can_count')
    # ### end Alembic commands ###
