"""Add 1 column at device model.

Revision ID: 59b340ef7918
Revises: e40ac9f2c587
Create Date: 2021-01-12 09:49:17.679939

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '59b340ef7918'
down_revision = 'e40ac9f2c587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('device_online_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'device_online_time')
    # ### end Alembic commands ###
