"""Initial migration.

Revision ID: 8213046de15c
Revises: 
Create Date: 2021-01-11 11:29:37.981448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8213046de15c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('backup_1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('backup_2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('backup_3', sa.VARCHAR(length=255), nullable=True),
    sa.Column('member_since', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('serial', sa.VARCHAR(length=50), nullable=False),
    sa.Column('customer', sa.VARCHAR(length=50), nullable=False),
    sa.Column('now_person_id', sa.Integer(), nullable=True),
    sa.Column('next_person_id', sa.Integer(), nullable=True),
    sa.Column('device_available_status', sa.Integer(), nullable=True),
    sa.Column('device_online_status', sa.Integer(), nullable=True),
    sa.Column('tips', sa.VARCHAR(length=255), nullable=True),
    sa.Column('backup_1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('backup_2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('backup_3', sa.VARCHAR(length=255), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['next_person_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['now_person_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    op.drop_table('users')
    # ### end Alembic commands ###
