"""Add 3 columns at device model.

Revision ID: e40ac9f2c587
Revises: 8213046de15c
Create Date: 2021-01-11 11:29:54.571401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40ac9f2c587'
down_revision = '8213046de15c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('can_count', sa.Integer(), nullable=False))
    op.add_column('device', sa.Column('license', sa.VARCHAR(length=50), nullable=False))
    op.add_column('device', sa.Column('lin_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'lin_count')
    op.drop_column('device', 'license')
    op.drop_column('device', 'can_count')
    # ### end Alembic commands ###
